---
- name: Install azure-cli on ubuntu 18.04
  hosts: Jenkins

  tasks:

    - name: sync ubuntu repo key
      shell: apt-key adv --keyserver keyserver.ubuntu.com --recv-keys FCEF32E745F2C3D5

    - name: install ubuntu packages
      apt:
        name: 
        - ca-certificates 
        - curl 
        - apt-transport-https 
        - lsb-release 
        - gnupg
        update_cache: yes

    ######## 

    - name: Install azure-cli | add microsoft pgp key 2
      shell: curl -sL https://packages.microsoft.com/keys/microsoft.asc |gpg --dearmor |tee /etc/apt/trusted.gpg.d/microsoft.asc.gpg > /dev/null

    - name: Install azure-cli | create azure apt list
      shell: |
        AZ_REPO=$(lsb_release -cs)
        echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" |
        sudo tee /etc/apt/sources.list.d/azure-cli.list

    - name: install azure-cli version 2.0.73-1~bionic from microsoft
      apt:
        name: 
        - azure-cli=2.0.73-1~bionic
        update_cache: yes
